version: '3.9'

networks:
  imbrett:

volumes:
  dbdata:
    driver: local

services:
  imbrett:
    build:
      context: ./
      dockerfile: ./docker/dev/nginx/Dockerfile
    container_name: nginx
    env_file: ./src/.env
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - postgres
      - mailhog
    networks:
      - imbrett

  imbrett-ui:
    image: ghcr.io/imbrett/imbrett_client:main

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: imbrett
      POSTGRES_USER: imbrett
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - imbrett

  php:
    build:
      context: ./
      dockerfile: ./docker/dev/php/Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
      - ./docker/dev/php/conf/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - imbrett

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - imbrett

  composer:
    build:
      context: ./
      dockerfile: ./docker/dev/composer/Dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: imbrett
    entrypoint: ['composer']
    networks:
      - imbrett

  artisan:
    build:
      context: ./
      dockerfile: ./docker/dev/php/Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html:delegated
      - ./docker/dev/php/conf/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    depends_on:
      - postgres
    user: imbrett
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - imbrett

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - imbrett
